# This workflow is used to check the differences and find conflict markers or whitespace errors

name: Black

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: psf/black@stable
      with:
        options: "--check --diff"
        src: "./pyiron_module"
